# GoReleaser configuration for bd-claim
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    - go mod tidy -compat=1.21

gomod:
  mod: mod

builds:
  - id: bd-claim-darwin-arm64
    main: ./cmd
    binary: bd-claim
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: bd-claim-archive
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Features"
      regexp: '^.*feat(\(\w+\))?:.*$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*fix(\(\w+\))?:.*$'
      order: 1
    - title: "Others"
      order: 999

release:
  github:
    owner: ccheney
    name: bd-claim
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## bd-claim v{{.Version}}

    Atomic issue claim CLI for multi-agent local swarms using Beads.

    ### Installation

    **Homebrew (macOS):**
    ```bash
    brew install ccheney/tap/bd-claim
    ```

    **Scoop (Windows):**
    ```powershell
    scoop bucket add ccheney https://github.com/ccheney/scoop-bucket
    scoop install bd-claim
    ```

    **Manual Install:**
    Download the appropriate binary for your platform below, extract it, and place it in your PATH.

    ### Usage

    ```bash
    bd-claim --agent <agent-name> --json
    ```

# Homebrew Tap
brews:
  - name: bd-claim
    repository:
      owner: ccheney
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://github.com/ccheney/bd-claim
    description: "Atomic issue claim CLI for multi-agent local swarms using Beads"
    license: MIT
    install: |
      bin.install "bd-claim"
    test: |
      system "#{bin}/bd-claim", "--version"

# Scoop Bucket
scoops:
  - name: bd-claim
    repository:
      owner: ccheney
      name: scoop-bucket
      branch: main
    homepage: https://github.com/ccheney/bd-claim
    description: "Atomic issue claim CLI for multi-agent local swarms using Beads"
    license: MIT
