# GoReleaser configuration for bd-claim
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bd-claim-linux-amd64
    main: ./cmd
    binary: bd-claim
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

  - id: bd-claim-linux-arm64
    main: ./cmd
    binary: bd-claim
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

  - id: bd-claim-darwin-amd64
    main: ./cmd
    binary: bd-claim
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

  - id: bd-claim-darwin-arm64
    main: ./cmd
    binary: bd-claim
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

  - id: bd-claim-windows-amd64
    main: ./cmd
    binary: bd-claim
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -buildmode=exe

archives:
  - id: bd-claim-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Features"
      regexp: '^.*feat(\(\w+\))?:.*$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*fix(\(\w+\))?:.*$'
      order: 1
    - title: "Others"
      order: 999

release:
  github:
    owner: ccheney
    name: bd-claim
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## bd-claim v{{.Version}}

    Atomic issue claim CLI for multi-agent local swarms using Beads.

    Pre-compiled binaries for Linux, macOS (Intel & Apple Silicon), and Windows.

    ### Installation

    **Manual Install:**
    Download the appropriate binary for your platform below, extract it, and place it in your PATH.

    ### Usage

    ```bash
    bd-claim --agent <agent-name> --json
    ```
